"""Offline domain rules for Japanese adult subtitle translation.

This module deliberately has no network or model dependency.  It provides a
curated, maintainer-authored phrase memory for high-risk short cues and fixed
common dialogue that compact models often mistranslate.  Phrase-memory lookup
is whole-cue and exact after conservative Unicode normalization; it never uses
substring or fuzzy matching.

Only subtitle text is accepted or returned.  Cue indices and timestamps never
enter this layer, so callers retain sole ownership of SRT structure.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Optional


DOMAIN_VERSION = "1.3.2"
DOMAIN_ENGINE_VERSION = DOMAIN_VERSION
GLOSSARY_VERSION = "2026.07.6"

_SOURCE_JAPANESE = frozenset({"ja", "ja-jp", "jp", "japanese", "日本語"})
_TARGET_ENGLISH = frozenset({"en", "en-us", "en-gb", "english"})
_TARGET_TAIWAN = frozenset(
    {
        "zh",
        "zh-tw",
        "zh-hant",
        "zh-hant-tw",
        "traditional-chinese",
        "taiwan",
        "繁體中文",
        "台灣繁中",
    }
)

_SPACE_RE = re.compile(r"\s+")
_SPACE_BEFORE_PUNCTUATION_RE = re.compile(r"\s+([,.;:!?、。！？])")
_SPACE_AFTER_OPENING_RE = re.compile(r"([「『（(\[]) +")
_SPACE_BEFORE_CLOSING_RE = re.compile(r" +([」』）)\]])")
_DECORATIVE_EDGE_RE = re.compile(r"^[.!…~〜～]+|[.!…~〜～]+$")
_OUTER_QUOTES = (
    ("「", "」"),
    ("『", "』"),
    ("“", "”"),
    ("‘", "’"),
    ('"', '"'),
)


def _language_key(value: object) -> str:
    return unicodedata.normalize("NFKC", str(value or "")).strip().lower().replace("_", "-")


def normalize_cue(text: object) -> str:
    """Return the conservative key used for exact whole-cue lookup.

    NFKC handles full-width Latin characters and half-width katakana.  Unicode
    whitespace is collapsed, Japanese comma/period are made comparable to
    their ASCII counterparts, matching outer quotation marks are removed, and
    purely stylistic edge punctuation is ignored.  Question marks are retained
    so grammatically explicit questions keep their original typography; the
    phrase memory never relies on punctuation alone to disambiguate a cue.
    """

    value = unicodedata.normalize("NFKC", str(text or ""))
    value = _SPACE_RE.sub(" ", value).strip()
    value = value.replace("、", ",").replace("。", ".")
    value = _SPACE_BEFORE_PUNCTUATION_RE.sub(r"\1", value)
    value = _SPACE_AFTER_OPENING_RE.sub(r"\1", value)
    value = _SPACE_BEFORE_CLOSING_RE.sub(r"\1", value)

    # Subtitle dialogue is often wrapped in Japanese quotation marks.  Remove
    # only a complete, balanced outer pair; internal quotes remain meaningful.
    for opening, closing in _OUTER_QUOTES:
        if len(value) >= 2 and value.startswith(opening) and value.endswith(closing):
            value = value[len(opening) : -len(closing)].strip()
            break

    # Periods, exclamation marks, ellipses, and tildes are stylistic at cue
    # edges.  A question mark is not stripped, and no punctuation inside the
    # cue is removed.
    previous = None
    while value != previous:
        previous = value
        value = _DECORATIVE_EDGE_RE.sub("", value).strip()
    return value


# Each entry is (Japanese source cue, English, Taiwan Traditional Chinese).
# These translations are original project text, not harvested subtitle data or
# output from a remote translation service.
_PHRASES = (
    # Consent, boundaries, and state.
    ("やめて", "Stop.", "停下來。"),
    ("止めて", "Stop.", "停下來。"),
    ("もうやめて", "Stop now.", "現在停下來。"),
    ("やめないで", "Don't stop.", "不要停。"),
    ("止めないで", "Don't stop.", "不要停。"),
    ("待って", "Wait.", "等一下。"),
    ("ちょっと待って", "Wait a moment.", "等一下。"),
    ("まだだめ", "Not yet.", "還不行。"),
    ("だめ", "No.", "不行。"),
    ("いや", "No.", "不要。"),
    ("無理", "I can't.", "我不行。"),
    ("離して", "Let go.", "放開。"),
    ("痛い", "It hurts.", "好痛。"),
    ("痛くない", "It doesn't hurt.", "不痛。"),
    ("痛くしないで", "Don't hurt me.", "不要弄痛我。"),
    ("気持ちいい", "It feels good.", "很舒服。"),
    ("気持ちよくない", "It doesn't feel good.", "不舒服。"),
    ("気持ちよかった", "That felt good.", "剛才很舒服。"),
    ("苦しい", "I'm in distress.", "我很難受。"),
    ("疲れた", "I'm tired.", "我累了。"),
    ("休ませて", "Let me rest.", "讓我休息一下。"),
    ("ちょっと休ませて", "Let me rest for a moment.", "讓我休息一下。"),
    ("やだ", "No.", "不要。"),
    ("嫌だ", "I don't want to.", "我不要。"),
    ("イヤ", "No.", "不要。"),
    ("ヤダ", "No.", "不要。"),
    ("いやです", "No.", "不要。"),
    ("ダメ", "No.", "不行。"),
    ("駄目", "No.", "不行。"),
    ("だめです", "No.", "不行。"),
    ("だめだよ", "No, you can't.", "不行。"),
    ("やめてよ", "Stop it.", "停下來。"),
    ("やめてください", "Please stop.", "請停下來。"),
    ("やめてぇ", "Stop.", "停下來。"),
    ("もうやめよう", "Let's stop.", "我們停下來吧。"),
    ("一旦やめて", "Stop for a moment.", "先停一下。"),
    ("一回止めて", "Stop for a moment.", "先停一下。"),
    ("止まって", "Stop.", "停下來。"),
    ("止まらないで", "Don't stop.", "不要停。"),
    ("やめなくていい", "You don't have to stop.", "不用停。"),
    ("やめないでよ", "Don't stop.", "不要停。"),
    ("本当にだめ", "Absolutely not.", "真的不行。"),
    ("絶対だめ", "Absolutely not.", "絕對不行。"),
    ("今はだめ", "Not now.", "現在不行。"),
    ("今は嫌", "I don't want to right now.", "我現在不想。"),
    ("まだだめです", "Not yet.", "還不行。"),
    ("もう無理", "I can't take any more.", "我不行了。"),
    ("これ以上は無理", "I can't take any more.", "我真的撐不下去了。"),
    ("本当に無理", "I really can't.", "我真的不行。"),
    ("できない", "I can't do it.", "我做不到。"),
    ("したくない", "I don't want to.", "我不想。"),
    ("終わりにして", "Please end this.", "請結束吧。"),
    ("今日はここまで", "Let's stop here for today.", "今天就到這裡。"),
    ("ここまでにして", "Let's stop here.", "到這裡就好。"),
    ("少し休みたい", "I want to rest a little.", "我想休息一下。"),
    ("休んで", "Take a break.", "休息一下。"),
    ("休もう", "Let's take a break.", "我們休息一下吧。"),
    ("ちょっと休もう", "Let's take a short break.", "我們休息一下吧。"),
    ("少し休んで", "Take a short break.", "休息一下。"),
    ("水飲みたい", "I want some water.", "我想喝水。"),
    ("水を飲ませて", "Let me drink some water.", "讓我喝點水。"),
    ("助けて", "Help me.", "幫幫我。"),
    ("押さえないで", "Don't hold me down.", "不要壓住我。"),
    ("手を離して", "Let go.", "放手。"),
    ("手を離さないで", "Don't let go.", "不要放手。"),
    ("動いて", "Move.", "動一下。"),
    ("動かないで", "Don't move.", "不要動。"),
    ("急に動かないで", "Don't move suddenly.", "不要突然動。"),
    ("何もしないで", "Don't do anything.", "什麼都不要做。"),
    ("無理しないで", "Don't push yourself.", "不要勉強自己。"),
    ("急いで", "Hurry.", "快一點。"),
    ("急がないで", "Don't rush.", "不要急。"),
    ("近くに来て", "Come closer.", "靠近一點。"),
    ("近づかないで", "Don't come closer.", "不要靠近。"),
    ("こっちに来ないで", "Don't come over here.", "不要過來這裡。"),
    ("怖い", "I'm scared.", "我害怕。"),
    ("怖くない", "I'm not scared.", "我不怕。"),
    ("怖がらないで", "Don't be afraid.", "不要害怕。"),
    ("落ち着いて", "Calm down.", "冷靜下來。"),
    ("深呼吸して", "Take a deep breath.", "深呼吸。"),
    ("息をして", "Breathe.", "呼吸。"),
    ("息を止めて", "Hold your breath.", "憋住呼吸。"),
    ("息を止めないで", "Don't hold your breath.", "不要憋氣。"),
    ("息できない", "I can't breathe.", "我沒辦法呼吸。"),
    ("息ができない", "I can't breathe.", "我沒辦法呼吸。"),
    ("息が苦しい", "I'm having trouble breathing.", "我呼吸有困難。"),
    ("気分が悪い", "I feel sick.", "我不舒服。"),
    ("吐きそう", "I feel like I'm going to be sick.", "我快吐了。"),
    ("大丈夫ですか?", "Is everything okay?", "都還好嗎？"),
    ("してもいい?", "May I?", "可以嗎？"),
    ("していい?", "Can I?", "可以嗎？"),
    ("してもいいよ", "You may.", "可以。"),
    ("本当にいいの?", "Is it really okay?", "真的可以嗎？"),
    ("いやじゃない", "I don't dislike it.", "我不討厭。"),
    ("これでいい?", "Is this okay?", "這樣可以嗎？"),
    ("このままでいい?", "Is it okay like this?", "就這樣可以嗎？"),
    ("続けていい?", "Can I keep going?", "可以繼續嗎？"),
    ("続けていいよ", "You can keep going.", "可以繼續。"),
    ("入れていい?", "Can I put it in?", "可以放進去嗎？"),
    ("触っていい?", "May I touch?", "可以碰嗎？"),
    ("キスしていい?", "May I kiss you?", "可以親你嗎？"),
    ("嫌だったら言って", "Tell me if you don't want this.", "不想要的話要跟我說。"),
    ("嫌ならやめる", "I'll stop if you don't want this.", "你不想的話我就停。"),
    ("痛かったら言って", "Tell me if it hurts.", "痛的話要跟我說。"),
    ("苦しかったら言って", "Tell me if you're in distress.", "如果很難受就跟我說。"),
    ("何かあったら言って", "Tell me if anything is wrong.", "有任何狀況就跟我說。"),
    ("苦しくない", "It isn't uncomfortable.", "不會難受。"),
    ("痛くしないから", "I won't hurt you.", "我不會弄痛你。"),
    ("痛くないようにする", "I'll be careful not to hurt you.", "我會小心不弄痛你。"),
    # Pace, intensity, and direction.
    ("続けて", "Keep going.", "繼續。"),
    ("そのまま", "Just like that.", "就這樣。"),
    ("速く", "Faster.", "快一點。"),
    ("もっと速く", "Faster.", "再快一點。"),
    ("ゆっくり", "Slowly.", "慢一點。"),
    ("もっとゆっくり", "Slower.", "再慢一點。"),
    ("強く", "Harder.", "用力一點。"),
    ("もっと強く", "Harder.", "再用力一點。"),
    ("弱く", "Softer.", "輕一點。"),
    ("もう少し弱く", "A little softer.", "再輕一點。"),
    ("優しくして", "Be gentle.", "溫柔一點。"),
    ("もっと優しく", "Be gentler.", "再溫柔一點。"),
    ("もっと", "More.", "再多一點。"),
    ("そこがいい", "That spot feels good.", "那裡很舒服。"),
    ("そこはだめ", "Not there.", "那裡不行。"),
    ("深すぎる", "That's too deep.", "太深了。"),
    ("もう一回", "One more time.", "再一次。"),
    ("早く", "Hurry up.", "快一點。"),
    ("もっと早く", "Hurry up.", "再快一點。"),
    ("速くして", "Go faster.", "快一點。"),
    ("もっと速くして", "Go faster.", "再快一點。"),
    ("ゆっくりして", "Go slowly.", "慢慢來。"),
    ("ゆっくりでいい", "Slow is fine.", "慢慢來就好。"),
    ("もっとゆっくりして", "Go more slowly.", "再慢一點。"),
    ("同じ速さで", "Keep the same pace.", "保持這個速度。"),
    ("その速さで", "Keep that pace.", "保持這個速度。"),
    ("一定の速さで", "Keep a steady pace.", "保持固定速度。"),
    ("強くして", "Use more force.", "用力一點。"),
    ("もっと強くして", "Use more force.", "再用力一點。"),
    ("強すぎる", "That's too hard.", "太用力了。"),
    ("弱くして", "Be softer.", "輕一點。"),
    ("弱すぎる", "That's too gentle.", "太輕了。"),
    ("優しく", "Be gentle.", "溫柔一點。"),
    ("もっと激しく", "More intensely.", "再激烈一點。"),
    ("激しくして", "Do it harder.", "激烈一點。"),
    ("乱暴にしないで", "Don't be rough.", "不要太粗暴。"),
    ("急にしないで", "Don't do it suddenly.", "不要突然來。"),
    ("その調子", "Keep it up.", "就是這樣。"),
    ("そのまま続けて", "Keep going like that.", "就這樣繼續。"),
    ("そのまま動いて", "Keep moving like that.", "就這樣繼續動。"),
    ("同じリズムで", "Keep the same rhythm.", "保持這個節奏。"),
    ("リズムを変えて", "Change the rhythm.", "換個節奏。"),
    ("リズムを変えないで", "Don't change the rhythm.", "不要改變節奏。"),
    ("リズム合わせて", "Match my rhythm.", "配合我的節奏。"),
    ("リズムを合わせて", "Match my rhythm.", "配合我的節奏。"),
    ("一緒に動いて", "Move with me.", "跟我一起動。"),
    ("一旦止まって", "Pause for a moment.", "先停一下。"),
    ("少し止まって", "Pause for a moment.", "稍微停一下。"),
    ("動きを止めて", "Stop moving.", "停下動作。"),
    ("動きを止めないで", "Don't stop moving.", "不要停下動作。"),
    ("もう少し", "A little more.", "再一點。"),
    ("少しだけ", "Just a little.", "一點點就好。"),
    ("深く", "Deeper.", "深一點。"),
    ("もっと深く", "Deeper.", "再深一點。"),
    ("もう少し奥", "A little deeper.", "再深一點。"),
    ("奥はだめ", "Not that deep.", "不要那麼深。"),
    ("浅くして", "Shallower.", "淺一點。"),
    ("もっと浅く", "Shallower.", "再淺一點。"),
    ("そこじゃない", "Not there.", "不是那裡。"),
    ("ここ", "Here.", "這裡。"),
    ("ここがいい", "Here feels good.", "這裡很舒服。"),
    ("ここはだめ", "Not here.", "這裡不行。"),
    ("どこがいい?", "Where feels good?", "哪裡舒服？"),
    ("どっちがいい?", "Which do you prefer?", "哪一個比較好？"),
    ("右", "To the right.", "往右。"),
    ("もう少し右", "A little to the right.", "再往右一點。"),
    ("左", "To the left.", "往左。"),
    ("もう少し左", "A little to the left.", "再往左一點。"),
    ("上", "Up.", "往上。"),
    ("もう少し上", "A little higher.", "再上面一點。"),
    ("下", "Down.", "往下。"),
    ("もう少し下", "A little lower.", "再下面一點。"),
    ("前", "Forward.", "往前。"),
    ("もっと前", "Farther forward.", "再往前一點。"),
    ("後ろ", "Back.", "往後。"),
    ("もっと後ろ", "Farther back.", "再往後一點。"),
    ("こっち", "This way.", "這邊。"),
    ("あっち", "That way.", "那邊。"),
    ("もっと近く", "Closer.", "再靠近一點。"),
    ("少し離れて", "Move a little farther away.", "稍微退開一點。"),
    ("もう少し離れて", "Move a little farther away.", "再退開一點。"),
    ("角度を変えて", "Change the angle.", "換個角度。"),
    ("角度を変えないで", "Don't change the angle.", "不要改變角度。"),
    ("その角度で", "Keep that angle.", "保持這個角度。"),
    ("その角度がいい", "That angle feels good.", "這個角度很舒服。"),
    ("反対側", "The other side.", "另一邊。"),
    ("腰を動かして", "Move your hips.", "動動腰。"),
    ("腰を動かさないで", "Don't move your hips.", "腰不要動。"),
    ("力を入れて", "Use some strength.", "用點力。"),
    ("力を入れないで", "Don't tense up.", "不要用力。"),
    ("力を抜いて", "Relax.", "放輕鬆。"),
    ("力を抜かないで", "Don't relax.", "不要放鬆。"),
    ("押して", "Push.", "推。"),
    ("押さないで", "Don't push.", "不要推。"),
    # Common adult-context dialogue.
    ("入れて", "Put it in.", "放進來。"),
    ("入れないで", "Don't put it in.", "不要放進來。"),
    ("中に出して", "Finish inside.", "射在裡面。"),
    ("中に出さないで", "Don't finish inside.", "不要射在裡面。"),
    ("触って", "Touch.", "碰一下。"),
    ("触らないで", "Don't touch.", "不要碰。"),
    ("見て", "Look.", "看。"),
    ("見ないで", "Don't look.", "不要看。"),
    ("キスして", "Kiss me.", "親我。"),
    ("脱いで", "Take it off.", "脫掉。"),
    ("脱がないで", "Don't take it off.", "不要脫。"),
    ("服を脱いで", "Take off your clothes.", "把衣服脫掉。"),
    ("下着を脱いで", "Take off your underwear.", "把內衣褲脫掉。"),
    ("足を開いて", "Spread your legs.", "把腿張開。"),
    ("もっと開いて", "Wider.", "再張開一點。"),
    ("声を出して", "Make some noise.", "出點聲。"),
    ("声を出さないで", "Don't make a sound.", "不要出聲。"),
    ("静かにして", "Be quiet.", "安靜一點。"),
    ("恥ずかしい", "This is embarrassing.", "好害羞。"),
    ("見えちゃう", "It'll be visible.", "會被看見。"),
    ("嫌じゃない", "I don't dislike it.", "我不討厭。"),
    ("愛してる", "I love you.", "我愛你。"),
    ("こっちに来て", "Come here.", "過來這裡。"),
    ("挿れて", "Put it in.", "放進來。"),
    ("挿れないで", "Don't put it in.", "不要放進來。"),
    ("入れてください", "Please put it in.", "請放進來。"),
    ("まだ入れないで", "Don't put it in yet.", "還不要放進來。"),
    ("ゆっくり入れて", "Put it in slowly.", "慢慢放進來。"),
    ("優しく入れて", "Put it in gently.", "輕輕放進來。"),
    ("奥まで入れて", "Put it all the way in.", "放到最裡面。"),
    ("全部入れて", "Put it all in.", "全部放進來。"),
    ("全部は無理", "I can't take all of it.", "沒辦法全部放進來。"),
    ("抜いて", "Pull it out.", "拔出來。"),
    ("抜かないで", "Don't pull it out.", "不要拔出去。"),
    ("中はだめ", "Not inside.", "裡面不行。"),
    ("中に出すよ", "I'm going to finish inside.", "我要射在裡面了。"),
    ("中に出していい?", "Can I finish inside?", "可以射在裡面嗎？"),
    ("中に出したらだめ", "Don't finish inside.", "不可以射在裡面。"),
    ("口の中に出して", "Finish in my mouth.", "射在我嘴裡。"),
    ("ゴムつけて", "Put on a condom.", "戴保險套。"),
    ("ゴムをつけて", "Put on a condom.", "戴保險套。"),
    ("ゴムして", "Use a condom.", "戴保險套。"),
    ("ゴムなしはだめ", "Not without a condom.", "沒戴保險套不行。"),
    ("コンドームをつけて", "Put on a condom.", "戴保險套。"),
    ("コンドームを外さないで", "Don't remove the condom.", "不要拿掉保險套。"),
    ("避妊して", "Use protection.", "做好避孕。"),
    ("妊娠しちゃう", "I'll get pregnant.", "這樣會懷孕。"),
    ("口を開けて", "Open your mouth.", "張開嘴。"),
    ("口を開けないで", "Don't open your mouth.", "不要張開嘴。"),
    ("舌を出して", "Stick out your tongue.", "把舌頭伸出來。"),
    ("舌を出さないで", "Don't stick out your tongue.", "不要伸出舌頭。"),
    ("舐めて", "Lick it.", "舔一下。"),
    ("舐めないで", "Don't lick it.", "不要舔。"),
    ("なめて", "Lick it.", "舔一下。"),
    ("なめないで", "Don't lick it.", "不要舔。"),
    ("乳首を吸って", "Suck my nipples.", "吸我的乳頭。"),
    ("乳首を吸わないで", "Don't suck my nipples.", "不要吸我的乳頭。"),
    ("軽く噛んで", "Bite gently.", "輕輕咬。"),
    ("噛まないで", "Don't bite.", "不要咬。"),
    ("咥えて", "Put it in your mouth.", "含住。"),
    ("私の口に入れて", "Put it in my mouth.", "放進我嘴裡。"),
    ("私の口に入れないで", "Don't put it in my mouth.", "不要放進我嘴裡。"),
    ("私の口から出して", "Take it out of my mouth.", "從我嘴裡拿出來。"),
    ("飲み込んで", "Swallow it.", "吞下去。"),
    ("飲み込まないで", "Don't swallow it.", "不要吞下去。"),
    ("手でして", "Use your hand.", "用手。"),
    ("口でして", "Use your mouth.", "用嘴。"),
    ("もっと触って", "Touch me more.", "再多摸我一點。"),
    ("そこを触って", "Touch there.", "碰那裡。"),
    ("胸を触って", "Touch the chest.", "摸胸部。"),
    ("乳首を触って", "Touch the nipples.", "摸乳頭。"),
    ("乳首を舐めて", "Lick the nipples.", "舔乳頭。"),
    ("髪を引っ張らないで", "Don't pull my hair.", "不要拉我的頭髮。"),
    ("叩かないで", "Don't hit me.", "不要打我。"),
    ("首を絞めないで", "Don't choke me.", "不要掐我的脖子。"),
    ("縛らないで", "Don't tie me up.", "不要綁我。"),
    ("もっとキスして", "Kiss me more.", "再多親我一點。"),
    ("キスしたい", "I want to kiss you.", "我想親你。"),
    ("キスしないで", "Don't kiss me.", "不要親我。"),
    ("抱きしめて", "Hold me.", "抱住我。"),
    ("抱きしめないで", "Don't hold me.", "不要抱我。"),
    ("そばにいて", "Stay with me.", "陪在我身邊。"),
    ("離れないで", "Don't move away.", "不要離開。"),
    ("名前を呼んで", "Say my name.", "叫我的名字。"),
    ("名前を呼ばないで", "Don't say my name.", "不要叫我的名字。"),
    ("こっち見て", "Look this way.", "看這邊。"),
    ("こっち見ないで", "Don't look this way.", "不要看這邊。"),
    ("目をそらさないで", "Don't look away.", "不要移開視線。"),
    ("顔を見せて", "Show your face.", "把臉露出來。"),
    ("気持ちいいね", "That feels good, doesn't it?", "很舒服吧。"),
    ("気持ちいいです", "It feels good.", "很舒服。"),
    ("すごく気持ちいい", "It feels amazing.", "非常舒服。"),
    ("気持ちよすぎる", "It feels too good.", "太舒服了。"),
    ("気持ちよくして", "Make me feel good.", "讓我舒服一點。"),
    ("お願い", "Please.", "拜託。"),
    ("お願いします", "Please.", "拜託了。"),
    ("おねがい", "Please.", "拜託。"),
    ("お願いだから", "Please, I'm begging you.", "拜託你。"),
    ("声が出ちゃう", "I can't help making noise.", "我會忍不住叫出聲。"),
    ("声を我慢できない", "I can't keep my voice down.", "我壓不住聲音。"),
    ("声を抑えられない", "I can't keep my voice down.", "我壓不住聲音。"),
    ("恥ずかしくて無理", "I'm too embarrassed.", "我太害羞了。"),
    ("緊張してる", "I'm nervous.", "我很緊張。"),
    ("緊張しないで", "Don't be nervous.", "不要緊張。"),
    ("準備できましたか?", "Are you ready?", "準備好了嗎？"),
    ("まだ準備できてない", "I'm not ready yet.", "我還沒準備好。"),
    # Clothing and pose directions.
    ("こっち向いて", "Face this way.", "面向這邊。"),
    ("後ろ向いて", "Turn around.", "轉過去。"),
    ("横向いて", "Turn to the side.", "側過身去。"),
    ("右を向いて", "Turn to the right.", "轉向右邊。"),
    ("左を向いて", "Turn to the left.", "轉向左邊。"),
    ("仰向けになって", "Lie on your back.", "仰躺。"),
    ("うつ伏せになって", "Lie face down.", "趴下。"),
    ("横向きになって", "Lie on your side.", "側躺。"),
    ("四つん這いになって", "Get on all fours.", "四肢著地。"),
    ("立って", "Stand up.", "站起來。"),
    ("座って", "Sit down.", "坐下。"),
    ("横になって", "Lie down.", "躺下。"),
    ("膝をついて", "Get on your knees.", "跪下。"),
    ("手をついて", "Brace yourself with your hands.", "用手撐著。"),
    ("足を上げて", "Raise your legs.", "把腿抬起來。"),
    ("足を下ろして", "Lower your legs.", "把腿放下。"),
    ("足を閉じて", "Close your legs.", "把腿合起來。"),
    ("足を広げて", "Spread your legs.", "把腿張開。"),
    ("もっと足を開いて", "Spread your legs wider.", "腿再張開一點。"),
    ("膝を曲げて", "Bend your knees.", "把膝蓋彎起來。"),
    ("膝を伸ばして", "Straighten your knees.", "把膝蓋伸直。"),
    ("腕を上げて", "Raise your arms.", "把手臂舉起來。"),
    ("腕を下ろして", "Lower your arms.", "把手臂放下。"),
    ("手を後ろに回して", "Put your hands behind you.", "把手放到身後。"),
    ("私の手を握って", "Hold my hand.", "握住我的手。"),
    ("目を閉じて", "Close your eyes.", "閉上眼睛。"),
    ("目を閉じないで", "Don't close your eyes.", "不要閉眼睛。"),
    ("目を開けて", "Open your eyes.", "睜開眼睛。"),
    ("目を開けないで", "Don't open your eyes.", "不要睜開眼睛。"),
    ("顔を上げて", "Raise your head.", "抬起頭。"),
    ("顔を下げて", "Lower your head.", "低下頭。"),
    ("顎を引いて", "Tuck your chin.", "下巴收一點。"),
    ("背中を反らして", "Arch your back.", "把背往後挺。"),
    ("腰を上げて", "Raise your hips.", "把臀部抬高。"),
    ("腰を下げて", "Lower your hips.", "把臀部放低。"),
    ("服を着て", "Put your clothes on.", "把衣服穿上。"),
    ("服は脱がないで", "Don't take your clothes off.", "不要脫衣服。"),
    ("シャツを脱いで", "Take off your shirt.", "把上衣脫掉。"),
    ("シャツは脱がないで", "Don't take off your shirt.", "不要脫上衣。"),
    ("ズボンを脱いで", "Take off your pants.", "把褲子脫掉。"),
    ("ズボンは脱がないで", "Don't take off your pants.", "不要脫褲子。"),
    ("下着は脱がないで", "Don't take off your underwear.", "不要脫內衣褲。"),
    ("ブラを外して", "Take off your bra.", "把胸罩脫掉。"),
    ("ブラは外さないで", "Don't take off your bra.", "不要脫胸罩。"),
    ("ボタンを外して", "Undo the buttons.", "把扣子解開。"),
    ("ボタンは外さないで", "Don't undo the buttons.", "不要解開扣子。"),
    ("ファスナーを開けて", "Open the zipper.", "把拉鍊拉開。"),
    ("ファスナーを閉めて", "Close the zipper.", "把拉鍊拉上。"),
    ("スカートを上げて", "Lift your skirt.", "把裙子拉高。"),
    ("スカートを下ろして", "Lower your skirt.", "把裙子放下。"),
    ("靴を脱いで", "Take off your shoes.", "把鞋子脫掉。"),
    ("靴下を脱いで", "Take off your socks.", "把襪子脫掉。"),
    # Camera, production, and privacy.
    ("カメラを見て", "Look at the camera.", "看著攝影機。"),
    ("カメラを見ないで", "Don't look at the camera.", "不要看攝影機。"),
    ("レンズを見て", "Look into the lens.", "看著鏡頭。"),
    ("レンズを見ないで", "Don't look into the lens.", "不要看鏡頭。"),
    ("カメラ回して", "Start recording.", "開始錄影。"),
    ("カメラを回して", "Start recording.", "開始錄影。"),
    ("カメラを回さないで", "Don't start the camera.", "不要開始錄影。"),
    ("カメラ止めて", "Stop recording.", "停止錄影。"),
    ("カメラは回っていますか?", "Is the camera rolling?", "攝影機有在拍嗎？"),
    ("もう撮影していますか?", "Are you already recording?", "已經在拍了嗎？"),
    ("動画を撮って", "Record a video.", "拍影片。"),
    ("動画を撮らないで", "Don't record a video.", "不要錄影。"),
    ("写真を撮って", "Take a picture.", "拍照。"),
    ("写真を撮らないで", "Don't take pictures.", "不要拍照。"),
    ("顔を映して", "Include the face in the shot.", "把臉拍進畫面。"),
    ("顔は映さないで", "Don't show the face.", "不要拍到臉。"),
    ("声は入れないで", "Don't capture any voices.", "不要錄到人聲。"),
    ("名前は出さないで", "Don't reveal the name.", "不要公開名字。"),
    ("本名は言わないで", "Don't say the real name.", "不要說出本名。"),
    ("個人情報は映さないで", "Don't show personal information.", "不要拍到個人資料。"),
    ("この部分は使わないで", "Don't use this part.", "不要使用這一段。"),
    ("ここはカットして", "Cut this part.", "這一段請剪掉。"),
    ("編集で消して", "Remove it in editing.", "後製時把這段刪掉。"),
    ("始めていい?", "Is it okay to start?", "可以開始嗎？"),
    ("始めます", "Starting now.", "現在開始。"),
    ("撮影始めます", "The shoot is starting.", "現在開始拍攝。"),
    ("撮影を始めます", "The shoot is starting.", "現在開始拍攝。"),
    ("撮影止めて", "Stop filming.", "停止拍攝。"),
    ("撮影を止めて", "Stop filming.", "停止拍攝。"),
    ("カット", "Cut.", "卡。"),
    ("もう一回お願いします", "One more time, please.", "麻煩再一次。"),
    ("撮り直して", "Shoot that again.", "重新拍一次。"),
    ("本番いきます", "Rolling.", "正式開拍。"),
    ("リハーサルです", "This is a rehearsal.", "現在是彩排。"),
    ("休憩にしよう", "Let's take a break.", "我們休息一下。"),
    ("水ください", "Water, please.", "請給我水。"),
    ("タオルください", "A towel, please.", "請給我毛巾。"),
    ("電気を消して", "Turn off the lights.", "把燈關掉。"),
    ("電気をつけて", "Turn on the lights.", "把燈打開。"),
    ("暗くして", "Make it darker.", "弄暗一點。"),
    ("明るくして", "Make it brighter.", "弄亮一點。"),
    ("照明を上げて", "Turn up the lights.", "把燈光調亮。"),
    ("照明を下げて", "Turn down the lights.", "把燈光調暗。"),
    ("ドアを閉めて", "Close the door.", "把門關上。"),
    ("ドアを開けないで", "Don't open the door.", "不要開門。"),
    ("鍵をかけて", "Lock the door.", "把門鎖上。"),
    ("誰か来る", "Someone's coming.", "有人要來了。"),
    ("誰かに見られる", "Someone might see.", "可能會被人看到。"),
    ("バレちゃう", "Someone will find out.", "會被人發現。"),
    ("マイクを近づけて", "Move the microphone closer.", "把麥克風靠近一點。"),
    ("音声は入っていますか?", "Is audio being captured?", "有錄到聲音嗎？"),
    ("ピントは合っていますか?", "Is it in focus?", "有對到焦嗎？"),
    ("もう少し右に立って", "Stand a little farther right.", "再往右站一點。"),
    ("もう少し左に立って", "Stand a little farther left.", "再往左站一點。"),
    # Common high-confidence ASR spellings.
    ("きもちいい", "It feels good.", "很舒服。"),
    ("気持いい", "It feels good.", "很舒服。"),
    ("気持ちい", "It feels good.", "很舒服。"),
    ("ちょっとまって", "Wait a moment.", "等一下。"),
    ("もうちょっと待って", "Wait a little longer.", "再等一下。"),
    ("もうちょっと", "A little more.", "再一點。"),
    ("さわって", "Touch.", "碰一下。"),
    ("さわらないで", "Don't touch.", "不要碰。"),
    ("なかに出して", "Finish inside.", "射在裡面。"),
    ("なかに出さないで", "Don't finish inside.", "不要射在裡面。"),
    ("脚を開いて", "Spread your legs.", "把腿張開。"),
    ("もっと脚を開いて", "Spread your legs wider.", "腿再張開一點。"),
    ("おくまで入れて", "Put it all the way in.", "放到最裡面。"),
)

# Explicit, maintainer-authored full cues.  These intentionally favor complete
# grammatical forms over ambiguous one-word overrides: the exact-memory layer
# should be most helpful when consent, safety, privacy, or production intent is
# actually present in the recognized text.
_EXPLICIT_DOMAIN_EXPANSION = (
    # Consent, refusal, distress, and check-ins.
    ("今すぐやめてください", "Please stop immediately.", "請立刻停下來。"),
    ("いったん全部止めてください", "Please stop everything for a moment.", "請先全部停一下。"),
    ("撮影を中止してください", "Please stop the shoot.", "請中止拍攝。"),
    ("同意していません", "I do not consent.", "我沒有同意。"),
    ("同意できない", "I cannot consent.", "我無法同意。"),
    ("撮影には同意していません", "I do not consent to being filmed.", "我不同意被拍攝。"),
    ("顔の撮影には同意していません", "I do not consent to having my face filmed.", "我不同意拍到我的臉。"),
    ("音声の収録には同意していません", "I do not consent to audio recording.", "我不同意錄音。"),
    ("同意を撤回します", "I withdraw my consent.", "我要撤回同意。"),
    ("やっぱりやめたい", "I want to stop after all.", "我還是想停下來。"),
    ("今日は撮影できません", "I cannot film today.", "我今天沒辦法拍攝。"),
    ("これ以上は続けられません", "I cannot continue any longer.", "我沒辦法再繼續了。"),
    ("この行為はしたくありません", "I do not want to do this act.", "我不想做這個行為。"),
    ("無理やりしないでください", "Please do not force me.", "請不要勉強我。"),
    ("許可なく触らないでください", "Please do not touch me without permission.", "沒有得到允許請不要碰我。"),
    ("触らないでください", "Please do not touch me.", "請不要碰我。"),
    ("それ以上触らないでください", "Please do not touch me any further.", "請不要再繼續碰我。"),
    ("私から離れてください", "Please move away from me.", "請離我遠一點。"),
    ("手首をつかまないでください", "Please do not grab my wrist.", "請不要抓住我的手腕。"),
    ("私の首に触れないでください", "Please do not touch my neck.", "請不要碰我的脖子。"),
    ("私の首を圧迫しないでください", "Please do not put pressure on my neck.", "請不要壓迫我的脖子。"),
    ("呼吸を妨げないでください", "Please do not restrict my breathing.", "請不要妨礙我呼吸。"),
    ("痛いのでやめてください", "Please stop because it hurts.", "很痛，請停下來。"),
    ("苦しいので止めてください", "Please stop because I am in distress.", "我很難受，請停下來。"),
    ("息ができないので止めてください", "Please stop because I cannot breathe.", "我無法呼吸，請停下來。"),
    ("気分が悪いので休ませてください", "I feel sick, so please let me rest.", "我不舒服，請讓我休息。"),
    ("めまいがします", "I feel dizzy.", "我覺得頭暈。"),
    ("吐き気がします", "I feel nauseous.", "我想吐。"),
    ("救急車呼んで", "Call an ambulance.", "叫救護車。"),
    ("血が出てる", "I'm bleeding.", "我在流血。"),
    ("意識がない", "They're unconscious.", "已經失去意識了。"),
    ("反応がない", "There's no response.", "沒有反應。"),
    ("胸が痛い", "My chest hurts.", "我胸口痛。"),
    ("水を飲む時間をください", "Please give me time to drink some water.", "請讓我喝點水。"),
    ("休憩が必要です", "I need a break.", "我需要休息。"),
    ("出血しているので止めてください", "Please stop because I am bleeding.", "我在流血，請停下來。"),
    ("痛みが強くなっています", "The pain is getting worse.", "疼痛正在加劇。"),
    ("手がしびれています", "My hand is numb.", "我的手麻了。"),
    ("足がしびれています", "My leg is numb.", "我的腿麻了。"),
    ("呼吸できるように緩めてください", "Please loosen it so I can breathe.", "請放鬆一點，讓我能呼吸。"),
    ("呼吸できていますか?", "Are you able to breathe?", "你能正常呼吸嗎？"),
    ("痛いところはありますか?", "Does anything hurt?", "有哪裡會痛嗎？"),
    ("休憩が必要ですか?", "Do you need a break?", "需要休息嗎？"),
    ("続ける前に確認してください", "Please check before continuing.", "繼續之前請先確認。"),
    ("嫌ならすぐに止めます", "I will stop immediately if you do not want this.", "如果你不想，我會立刻停下來。"),
    ("痛みがあればすぐに止めます", "I will stop immediately if there is any pain.", "只要會痛，我就立刻停下來。"),
    ("苦しくなったらすぐに止めます", "I will stop immediately if you are in distress.", "只要你覺得難受，我就立刻停下來。"),
    ("合図をしたら止めてください", "Please stop when I give the signal.", "我發出信號時請停下來。"),
    ("手を上げたら止めてください", "Please stop when I raise my hand.", "我舉手時請停下來。"),
    ("「ストップ」と言ったら止めてください", "Please stop when I say “stop.”", "我說「停」時請停下來。"),
    ("合図が聞こえたら止めてください", "Please stop when you hear the signal.", "聽到信號時請停下來。"),
    ("私の返事を待ってください", "Please wait for my answer.", "請等我回答。"),
    ("返事をするまで始めないでください", "Please do not start until I answer.", "在我回答之前請不要開始。"),
    ("同意を確認してから始めてください", "Please confirm consent before starting.", "開始之前請先確認同意。"),
    ("毎回確認してから続けてください", "Please check each time before continuing.", "每次繼續前都請先確認。"),
    ("続けることに同意します", "I consent to continuing.", "我同意繼續。"),
    ("撮影を始めてもいいですか?", "Is it okay to start filming?", "可以開始拍攝嗎？"),
    ("録音を始めてもいいですか?", "Is it okay to start recording audio?", "可以開始錄音嗎？"),
    ("顔を撮ってもいいですか?", "Is it okay to film the face?", "可以拍到臉嗎？"),
    ("本名を出してもいいですか?", "Is it okay to reveal the real name?", "可以公開本名嗎？"),
    ("この映像を公開してもいいですか?", "Is it okay to publish this footage?", "可以公開這段影像嗎？"),
    ("この部分を使ってもいいですか?", "Is it okay to use this part?", "可以使用這一段嗎？"),
    ("ここに触ってもいいですか?", "Is it okay to touch here?", "可以碰這裡嗎？"),
    ("キスしてもいいですか?", "May I kiss you?", "可以親你嗎？"),
    ("録画を開始してもいいですか?", "Is it okay to start recording?", "可以開始錄影嗎？"),
    ("音声を公開してもいいですか?", "Is it okay to publish the audio?", "可以公開這段聲音嗎？"),
    ("撮影日を公開してもいいですか?", "Is it okay to reveal the filming date?", "可以公開拍攝日期嗎？"),
    ("予定にないことはしないでください", "Please do not do anything that was not planned.", "請不要做事前沒有安排的事。"),
    ("事前に決めたことだけにしてください", "Please only do what was agreed beforehand.", "請只做事前約定好的事。"),
    ("同意した範囲だけにしてください", "Please stay within what I consented to.", "請只做我同意範圍內的事。"),
    ("勝手に変更しないでください", "Please do not change anything without permission.", "請不要擅自更改。"),
    # Protection and explicit-object adult safety.
    ("ゴムなしではしません", "I will not do it without a condom.", "沒有保險套我不會做。"),
    ("コンドームが破れていないか確認してください", "Please check that the condom is not torn.", "請確認保險套沒有破。"),
    ("コンドームを新しいものに替えてください", "Please replace the condom with a new one.", "請換一個新的保險套。"),
    ("コンドームを着けるまで入れないで", "Do not put it in until the condom is on.", "戴好保險套之前不要放進來。"),
    ("コンドームを着けてから始めて", "Put on a condom before starting.", "戴好保險套再開始。"),
    ("コンドームが破れたらすぐに止めて", "Stop immediately if the condom tears.", "保險套破掉就立刻停下來。"),
    ("コンドームが外れたらすぐに止めて", "Stop immediately if the condom comes off.", "保險套脫落就立刻停下來。"),
    ("コンドームが破れた", "The condom broke.", "保險套破了。"),
    ("コンドームが外れた", "The condom came off.", "保險套脫落了。"),
    ("まだ射精しないで", "Do not ejaculate yet.", "還不要射精。"),
    ("膣内に射精してもいいですか?", "May I ejaculate inside the vagina?", "可以在陰道內射精嗎？"),
    ("中には出さないでください", "Please do not finish inside.", "請不要射在裡面。"),
    ("膣内に射精しないでください", "Please do not ejaculate inside the vagina.", "請不要在陰道內射精。"),
    ("膣内射精には同意していません", "I do not consent to vaginal ejaculation.", "我不同意在陰道內射精。"),
    ("妊娠の可能性があるのでやめて", "Stop because there is a risk of pregnancy.", "有懷孕的風險，請停下來。"),
    ("避妊できているか確認してください", "Please check that contraception is in place.", "請確認已做好避孕措施。"),
    ("潤滑剤をもう少し使って", "Use a little more lubricant.", "再多用一點潤滑劑。"),
    ("潤滑剤を追加してください", "Please add more lubricant.", "請再補充潤滑劑。"),
    ("乾いているから痛い", "It hurts because it is dry.", "因為太乾所以會痛。"),
    ("痛い場所には触らないで", "Do not touch the painful area.", "不要碰會痛的地方。"),
    ("私の胸には触らないで", "Do not touch my chest.", "不要碰我的胸部。"),
    ("私の顔には触らないで", "Do not touch my face.", "不要碰我的臉。"),
    ("私の首には触らないで", "Do not touch my neck.", "不要碰我的脖子。"),
    ("私の髪を引っ張らないで", "Do not pull my hair.", "不要拉我的頭髮。"),
    ("私のお尻を叩かないで", "Do not spank me.", "不要拍打我的臀部。"),
    ("私を縛らないで", "Do not tie me up.", "不要綁住我。"),
    ("この縄を解いて", "Untie this rope.", "把這條繩子解開。"),
    ("首を絞めることには同意しません", "I do not consent to choking.", "我不同意掐脖子。"),
    ("縛ることには同意しません", "I do not consent to being tied up.", "我不同意被綁住。"),
    ("撮影されることには同意しません", "I do not consent to being filmed.", "我不同意被拍攝。"),
    ("顔を出すことには同意しません", "I do not consent to showing my face.", "我不同意露臉。"),
    ("本名を出すことには同意しません", "I do not consent to revealing my real name.", "我不同意公開本名。"),
    ("音声を公開することには同意しません", "I do not consent to publishing the audio.", "我不同意公開聲音。"),
    ("この映像の公開には同意しません", "I do not consent to publishing this footage.", "我不同意公開這段影像。"),
    ("私の顔には射精しないで", "Do not ejaculate on my face.", "不要射精在我臉上。"),
    ("私の胸には射精しないで", "Do not ejaculate on my chest.", "不要射精在我胸前。"),
    ("私のお腹には射精しないで", "Do not ejaculate on my stomach.", "不要射精在我肚子上。"),
    ("私の口の中には射精しないで", "Do not ejaculate in my mouth.", "不要射精在我嘴裡。"),
    ("私の顔に射精して", "Ejaculate on my face.", "射精在我臉上。"),
    ("私の胸に射精して", "Ejaculate on my chest.", "射精在我胸前。"),
    ("私のお腹に射精して", "Ejaculate on my stomach.", "射精在我肚子上。"),
    ("私を抱きしめて", "Hold me.", "抱住我。"),
    ("私の名前を呼んで", "Say my name.", "叫我的名字。"),
    ("私の名前を呼ばないで", "Do not say my name.", "不要叫我的名字。"),
    ("私の胸を触って", "Touch my chest.", "摸我的胸部。"),
    ("私の乳首を触って", "Touch my nipples.", "摸我的乳頭。"),
    ("私の乳首を舐めて", "Lick my nipples.", "舔我的乳頭。"),
    ("私の首を絞めないで", "Do not choke me.", "不要掐我的脖子。"),
    # Pace, placement, and pose with explicit modifiers.
    ("もう少し速度を落として", "Slow down a little more.", "再放慢一點。"),
    ("その速度を保って", "Keep that speed.", "保持這個速度。"),
    ("一度完全に止まって", "Stop completely for a moment.", "先完全停下來。"),
    ("ゆっくり再開して", "Resume slowly.", "慢慢重新開始。"),
    ("合図するまで動かないで", "Do not move until I give the signal.", "在我發出信號前不要動。"),
    ("合図したら動いて", "Move when I give the signal.", "我發出信號後再動。"),
    ("急に深くしないで", "Do not go deep suddenly.", "不要突然變深。"),
    ("浅いところだけにして", "Keep it shallow.", "只要淺一點就好。"),
    ("奥まで入れないで", "Do not put it all the way in.", "不要放到最裡面。"),
    ("深さを変えないで", "Do not change the depth.", "不要改變深度。"),
    ("角度を少し上に変えて", "Angle it slightly upward.", "把角度稍微往上調。"),
    ("角度を少し下に変えて", "Angle it slightly downward.", "把角度稍微往下調。"),
    ("右に少しずらして", "Shift it slightly to the right.", "稍微往右移。"),
    ("左に少しずらして", "Shift it slightly to the left.", "稍微往左移。"),
    ("体を少し前に出して", "Move your body slightly forward.", "身體稍微往前。"),
    ("体を少し後ろに下げて", "Move your body slightly back.", "身體稍微往後。"),
    ("私に合わせて動いて", "Move in sync with me.", "配合我的動作。"),
    ("呼吸に合わせて動いて", "Move in time with the breathing.", "配合呼吸動作。"),
    ("一定のリズムを保って", "Keep a steady rhythm.", "保持固定節奏。"),
    ("そのリズムのまま続けて", "Continue with that rhythm.", "保持這個節奏繼續。"),
    ("力を少し弱めて", "Use a little less force.", "力道再小一點。"),
    ("もっと優しく触って", "Touch me more gently.", "再溫柔一點碰我。"),
    ("強く押さえないで", "Do not hold me down tightly.", "不要用力壓住我。"),
    ("手の力を緩めて", "Loosen your grip.", "手放鬆一點。"),
    ("腰をもう少し上げて", "Raise your hips a little more.", "臀部再抬高一點。"),
    ("肩の力を抜いて", "Relax your shoulders.", "肩膀放鬆。"),
    ("背中をまっすぐにして", "Straighten your back.", "把背挺直。"),
    ("頭を少し右に向けて", "Turn your head slightly to the right.", "頭稍微轉向右邊。"),
    ("頭を少し左に向けて", "Turn your head slightly to the left.", "頭稍微轉向左邊。"),
    ("顎をもう少し上げて", "Raise your chin a little more.", "下巴再抬高一點。"),
    ("顎をもう少し下げて", "Lower your chin a little more.", "下巴再降低一點。"),
    ("両膝を少し開いて", "Spread both knees slightly.", "雙膝稍微張開。"),
    ("両足をそろえて", "Put both feet together.", "雙腳併攏。"),
    ("右足だけ上げて", "Raise only your right leg.", "只抬起右腿。"),
    ("左足だけ上げて", "Raise only your left leg.", "只抬起左腿。"),
    ("右手を頭の上に置いて", "Put your right hand above your head.", "把右手放到頭上。"),
    ("左手を腰に置いて", "Put your left hand on your hip.", "把左手放在腰上。"),
    ("両手を見える位置に置いて", "Keep both hands where they can be seen.", "把雙手放在看得到的位置。"),
    ("手で顔を隠さないで", "Do not cover your face with your hands.", "不要用手遮住臉。"),
    ("髪で顔を隠さないで", "Do not let your hair cover your face.", "不要讓頭髮遮住臉。"),
    ("体をカメラのほうに向けて", "Turn your body toward the camera.", "身體轉向攝影機。"),
    ("肩を少し後ろに引いて", "Pull your shoulders slightly back.", "肩膀稍微往後。"),
    ("背中を丸めないで", "Do not round your back.", "不要駝背。"),
    ("腰の位置を変えないで", "Do not change the position of your hips.", "不要改變臀部的位置。"),
    ("足の位置を変えないで", "Do not move your feet.", "不要改變腳的位置。"),
    # Recording, framing, privacy, and retakes.
    ("録画を開始してください", "Please start recording.", "請開始錄影。"),
    ("録画を停止してください", "Please stop recording.", "請停止錄影。"),
    ("音声の録音を開始してください", "Please start recording audio.", "請開始錄音。"),
    ("音声の録音を停止してください", "Please stop recording audio.", "請停止錄音。"),
    ("カメラが回っているか確認してください", "Please check that the camera is rolling.", "請確認攝影機正在錄影。"),
    ("音声が録れているか確認してください", "Please check that the audio is recording.", "請確認有錄到聲音。"),
    ("マイクの音量を確認してください", "Please check the microphone level.", "請確認麥克風音量。"),
    ("マイクを少し離してください", "Please move the microphone a little farther away.", "請把麥克風稍微移遠。"),
    ("マイクを画面から外してください", "Please keep the microphone out of the frame.", "請不要讓麥克風出現在畫面裡。"),
    ("カメラを少し近づけて", "Move the camera a little closer.", "把攝影機移近一點。"),
    ("カメラを少し遠ざけて", "Move the camera a little farther away.", "把攝影機移遠一點。"),
    ("カメラを固定してください", "Please keep the camera fixed.", "請把攝影機固定好。"),
    ("カメラを動かさないでください", "Please do not move the camera.", "請不要移動攝影機。"),
    ("カメラを右に振ってください", "Please pan the camera to the right.", "請把攝影機往右移動。"),
    ("カメラを左に振ってください", "Please pan the camera to the left.", "請把攝影機往左移動。"),
    ("もう少し引きで撮ってください", "Please use a slightly wider shot.", "請把畫面再拉遠一點。"),
    ("もう少し寄りで撮ってください", "Please use a slightly tighter shot.", "請把畫面再拉近一點。"),
    ("全身が入るように撮ってください", "Please frame the whole body.", "請把全身拍進畫面。"),
    ("顔が画面に入るようにしてください", "Please keep the face in the frame.", "請讓臉保持在畫面內。"),
    ("顔が映らないようにしてください", "Please keep the face out of the shot.", "請不要拍到臉。"),
    ("背景を映さないでください", "Please do not show the background.", "請不要拍到背景。"),
    ("部屋の中を映さないでください", "Please do not show the room.", "請不要拍到房間內部。"),
    ("時計を映さないでください", "Please do not show the clock.", "請不要拍到時鐘。"),
    ("窓の外を映さないでください", "Please do not show the view outside the window.", "請不要拍到窗外。"),
    ("名札を映さないでください", "Please do not show the name tag.", "請不要拍到名牌。"),
    ("住所が映らないようにしてください", "Please make sure the address is not visible.", "請確保地址不會出現在畫面裡。"),
    ("個人情報をぼかしてください", "Please blur the personal information.", "請把個人資料模糊處理。"),
    ("顔にモザイクをかけてください", "Please pixelate the face.", "請在臉上加馬賽克。"),
    ("本名を音声から消してください", "Please remove the real name from the audio.", "請從聲音中刪除本名。"),
    ("この発言はカットしてください", "Please cut this remark.", "請剪掉這句話。"),
    ("この場面は公開しないでください", "Please do not publish this scene.", "請不要公開這個場景。"),
    ("この映像は削除してください", "Please delete this footage.", "請刪除這段影像。"),
    ("公開前に確認させてください", "Please let me review it before publication.", "公開前請讓我確認。"),
    ("サムネイルに顔を使わないでください", "Please do not use my face in the thumbnail.", "請不要在縮圖中使用我的臉。"),
    ("タイトルに本名を入れないでください", "Please do not put my real name in the title.", "請不要在標題中放入我的本名。"),
    ("音声を加工してください", "Please alter the audio.", "請處理聲音。"),
    ("声が分からないように加工してください", "Please disguise the voice so it cannot be recognized.", "請把聲音處理到無法辨認。"),
    ("位置情報を削除してください", "Please remove the location information.", "請刪除位置資訊。"),
    ("撮影日を公開しないでください", "Please do not reveal the filming date.", "請不要公開拍攝日期。"),
    ("スタッフ以外は部屋から出てください", "Everyone except the staff must leave the room.", "工作人員以外的人請離開房間。"),
    ("ドアが閉まっているか確認してください", "Please check that the door is closed.", "請確認門已關好。"),
    ("外から見えないようにカーテンを閉めてください", "Please close the curtains so no one can see in.", "請把窗簾關上，避免外面的人看到。"),
    ("鍵がかかっているか確認してください", "Please check that the door is locked.", "請確認門已上鎖。"),
    ("撮影中の表示を出してください", "Please put up the filming-in-progress sign.", "請掛出拍攝中的告示。"),
    ("録音中の表示を確認してください", "Please check the recording indicator.", "請確認錄音中的指示燈。"),
    ("テイク番号を言ってください", "Please say the take number.", "請說出拍攝次數編號。"),
    ("次のテイクを始めます", "We are starting the next take.", "現在開始下一次拍攝。"),
    ("このテイクをやり直します", "We will redo this take.", "這次拍攝要重來。"),
    ("最初から撮り直してください", "Please reshoot it from the beginning.", "請從頭重新拍攝。"),
    ("さっきの位置に戻ってください", "Please return to the previous position.", "請回到剛才的位置。"),
    ("マークの位置に立ってください", "Please stand on the mark.", "請站在標記的位置。"),
    ("画角を変えないでください", "Please do not change the framing.", "請不要改變取景範圍。"),
    ("ピントを顔に合わせてください", "Please focus on the face.", "請把焦點對在臉上。"),
    ("ピントを手元に合わせてください", "Please focus on the hands.", "請把焦點對在手部。"),
    ("露出を少し下げてください", "Please lower the exposure slightly.", "請把曝光稍微調低。"),
    ("露出を少し上げてください", "Please raise the exposure slightly.", "請把曝光稍微調高。"),
    ("照明をもう少し柔らかくしてください", "Please make the lighting a little softer.", "請把燈光調得再柔和一點。"),
    ("影が顔にかからないようにしてください", "Please keep the shadow off the face.", "請不要讓陰影遮到臉。"),
    ("ノイズが入っているので止めてください", "Please stop because there is noise in the recording.", "錄音有雜音，請停一下。"),
    ("マイクに触らないでください", "Please do not touch the microphone.", "請不要碰麥克風。"),
    ("もう一度セリフをお願いします", "Please repeat the line.", "請再說一次台詞。"),
    ("最初のセリフからお願いします", "Please start again from the first line.", "請從第一句台詞重新開始。"),
    ("もう少し大きな声でお願いします", "Please speak a little louder.", "請再大聲一點。"),
    ("もう少し小さな声でお願いします", "Please speak a little more softly.", "請再小聲一點。"),
    ("カメラのほうを見てください", "Please look toward the camera.", "請看向攝影機。"),
    ("レンズの少し右を見てください", "Please look slightly to the right of the lens.", "請看鏡頭右側一點。"),
    ("レンズの少し左を見てください", "Please look slightly to the left of the lens.", "請看鏡頭左側一點。"),
    ("録画を開始します", "Recording will start.", "現在開始錄影。"),
    ("録音を始めます", "Audio recording will start.", "現在開始錄音。"),
    ("顔を撮ります", "The face will be filmed.", "接下來會拍到臉。"),
    ("本名を出します", "The real name will be revealed.", "接下來會公開本名。"),
    ("この映像を公開します", "This footage will be published.", "這段影像將會公開。"),
    ("この部分を使います", "This part will be used.", "這一段將會使用。"),
    ("音声を公開します", "The audio will be published.", "這段聲音將會公開。"),
    ("撮影日を公開します", "The filming date will be revealed.", "拍攝日期將會公開。"),
)
_PHRASES += _EXPLICIT_DOMAIN_EXPANSION

# Additional reviewed coverage for emergency stop language, performer privacy,
# camera blocking, and common kana-only ASR output.  These are still exact
# whole-cue matches; no substring or fuzzy expansion is performed.
_SPECIALIZED_DOMAIN_EXPANSION = (
    # Emergency, consent, medical, and protection language.
    ("今すぐ全部の動きを止めて", "Stop all movement right now.", "現在立刻停止所有動作。"),
    ("撮影を今すぐ中止してください", "Please stop the shoot immediately.", "請立刻停止拍攝。"),
    ("この行為には同意していません", "I do not consent to this act.", "我不同意這個行為。"),
    ("撮影されることには同意していません", "I do not consent to being filmed.", "我不同意被拍攝。"),
    ("音声を録音されることには同意していません", "I do not consent to having audio recorded.", "我不同意被錄音。"),
    ("顔出しには同意していません", "I do not consent to showing my face.", "我不同意露臉。"),
    ("コンドームなしの行為には同意しません", "I do not consent to sex without a condom.", "我不同意無套性行為。"),
    ("今から同意を撤回します", "I am withdrawing my consent now.", "我現在撤回同意。"),
    ("赤と言ったら全部止めて", "If I say red, stop everything.", "我說「紅色」時就全部停下來。"),
    ("返事がなかったら動きを止めて", "Stop moving if there is no response.", "如果沒有回應就停止動作。"),
    ("嫌になったらすぐに言って", "Say so immediately if you no longer want this.", "如果不想繼續就立刻說。"),
    ("やめたくなったら手を上げて", "Raise your hand if you want to stop.", "想停下來時就舉手。"),
    ("話せないときは手を二回叩いて", "Clap your hands twice if you cannot speak.", "無法說話時就拍手兩次。"),
    ("合図ができる状態ですか?", "Are you able to signal?", "現在能發出信號嗎？"),
    ("意識ははっきりしていますか?", "Are you fully conscious?", "意識清楚嗎？"),
    ("指示は聞こえていますか?", "Can you hear the instructions?", "聽得到指示嗎？"),
    ("続けても大丈夫ですか?", "Is it okay to continue?", "可以繼續嗎？"),
    ("この体位を続けても大丈夫ですか?", "Is it okay to continue this position?", "可以繼續這個姿勢嗎？"),
    ("体位を変えても大丈夫ですか?", "Is it okay to change positions?", "可以換姿勢嗎？"),
    ("コンドームを着けていますか?", "Is a condom in place?", "有戴好保險套嗎？"),
    ("もう一度同意を確認して", "Confirm consent again.", "再確認一次同意。"),
    ("この体位はやりたくない", "I do not want this position.", "我不想做這個姿勢。"),
    ("首を絞めるのはやめて", "Stop choking.", "不要再掐脖子。"),
    ("顔を叩かないで", "Do not hit the face.", "不要打臉。"),
    ("手首を強く掴まないで", "Do not grip the wrists tightly.", "不要用力抓手腕。"),
    ("腕をねじらないで", "Do not twist the arms.", "不要扭手臂。"),
    ("私の胸に体重をかけないで", "Do not put your weight on my chest.", "不要把重量壓在我胸口。"),
    ("傷口に触らないで", "Do not touch the wound.", "不要碰傷口。"),
    ("無理やり入れないで", "Do not force it in.", "不要硬塞進去。"),
    ("急に奥まで入れないで", "Do not push it all the way in suddenly.", "不要突然放到最深處。"),
    ("これ以上奥に入れないで", "Do not push it in any deeper.", "不要再放得更深。"),
    ("肛門には入れないで", "Do not insert it into the anus.", "不要放進肛門。"),
    ("膣内には出さないで", "Do not ejaculate in the vagina.", "不要射在陰道內。"),
    ("コンドームがずれています", "The condom has slipped.", "保險套移位了。"),
    ("新しいコンドームに替えて", "Change to a new condom.", "換一個新的保險套。"),
    ("潤滑が足りなくて痛い", "It hurts because there is not enough lubrication.", "潤滑不夠，很痛。"),
    ("爪を立てないで", "Do not dig your nails in.", "不要用指甲抓。"),
    ("医療スタッフを呼んで", "Call the medical staff.", "請叫醫療人員來。"),
    ("救急車を呼んでください", "Please call an ambulance.", "請叫救護車。"),
    ("口と鼻を同時に塞がないで", "Do not cover the mouth and nose at the same time.", "不要同時摀住口鼻。"),
    ("首に圧力をかけないで", "Do not put pressure on the neck.", "不要壓迫脖子。"),
    ("胸を圧迫しないで", "Do not compress the chest.", "不要壓迫胸口。"),
    ("首から手を離して", "Take your hand off the neck.", "把手從脖子上移開。"),
    ("息が吸えない", "I cannot breathe in.", "我吸不到氣。"),
    ("息が吐けない", "I cannot breathe out.", "我吐不出氣。"),
    ("喉が締まって息ができない", "I cannot breathe because my throat is constricted.", "喉嚨被壓住，無法呼吸。"),
    ("胸が苦しくて息ができない", "I cannot breathe because my chest feels tight.", "胸口很悶，無法呼吸。"),
    ("呼吸が浅くなっています", "Breathing is becoming shallow.", "呼吸變淺了。"),
    ("呼吸を確認してください", "Please check breathing.", "請確認呼吸狀況。"),
    ("意識があるか確認してください", "Please check for consciousness.", "請確認意識狀況。"),
    ("息を整える時間をください", "Please give me time to catch my breath.", "請給我一點時間調整呼吸。"),
    ("吐きそうだから動きを止めて", "Stop moving because I may vomit.", "我快吐了，先停止動作。"),
    ("痛みが引きません", "The pain is not subsiding.", "疼痛沒有緩解。"),
    ("手首がしびれてきた", "My wrists are going numb.", "我的手腕開始發麻。"),
    ("足に力が入らなくて立てない", "I cannot stand because my legs have no strength.", "雙腿使不上力，站不起來。"),
    ("ロープがきつすぎる", "The rope is too tight.", "繩子綁得太緊。"),
    ("手首の縄を緩めて", "Loosen the rope around the wrists.", "把手腕上的繩子鬆開一點。"),
    ("拘束具を緩めて", "Loosen the restraints.", "把拘束具鬆開一點。"),
    ("しびれが出たら拘束を外して", "Remove the restraints if numbness starts.", "出現麻木就解除拘束。"),
    ("痛みがあるのでこの体位をやめてください", "Please stop this position because it is painful.", "這個姿勢會痛，請停止。"),
    ("体調が悪いので撮影を中止してください", "Please stop the shoot because I feel unwell.", "身體不舒服，請停止拍攝。"),
    ("私が返事できない場合は撮影を止めて", "Stop filming if I cannot respond.", "如果我無法回應，就停止拍攝。"),
    ("誰かが意識を失ったら救急車を呼んで", "Call an ambulance if anyone loses consciousness.", "有人失去意識就叫救護車。"),
    # Identity, privacy, publication, and retention.
    ("顔全体は映さないで", "Do not show the full face.", "不要拍到整張臉。"),
    ("目元は映さないで", "Do not show the eye area.", "不要拍到眼睛周圍。"),
    ("顔にモザイクをかけて", "Pixelate the face.", "幫臉部打馬賽克。"),
    ("顔をぼかして", "Blur the face.", "把臉部模糊處理。"),
    ("背景をぼかして", "Blur the background.", "把背景模糊處理。"),
    ("タトゥーは映さないで", "Do not show the tattoos.", "不要拍到刺青。"),
    ("身分証は映さないで", "Do not show the identification document.", "不要拍到身分證件。"),
    ("住所が見える物は映さないで", "Do not show anything displaying an address.", "不要拍到會顯示地址的物品。"),
    ("スマホの画面は映さないで", "Do not show the phone screen.", "不要拍到手機畫面。"),
    ("通知画面は映さないで", "Do not show notification screens.", "不要拍到通知畫面。"),
    ("車のナンバーは映さないで", "Do not show the license plate.", "不要拍到車牌。"),
    ("窓の外は映さないで", "Do not show the view outside the window.", "不要拍到窗外景色。"),
    ("撮影場所が分からないようにして", "Make sure the filming location cannot be identified.", "不要讓人辨認出拍攝地點。"),
    ("動画の位置情報を削除して", "Remove location metadata from the video.", "刪除影片的位置資訊。"),
    ("写真の位置情報を削除して", "Remove location metadata from the photos.", "刪除照片的位置資訊。"),
    ("音声を変えて公開して", "Alter the voice before publishing.", "變更聲音後再公開。"),
    ("音声は収録しないで", "Do not record audio.", "不要收錄音訊。"),
    ("この会話は録音しないで", "Do not record this conversation.", "不要錄下這段對話。"),
    ("マイクを切って", "Turn off the microphone.", "關掉麥克風。"),
    ("録音を一旦止めて", "Pause the audio recording.", "暫停錄音。"),
    ("録画を一旦止めて", "Pause the video recording.", "暫停錄影。"),
    ("まだ録画を始めないで", "Do not start recording yet.", "還不要開始錄影。"),
    ("カメラが止まっているか確認して", "Confirm that the camera has stopped recording.", "確認攝影機已停止錄影。"),
    ("マイクが切れているか確認して", "Confirm that the microphone is off.", "確認麥克風已關閉。"),
    ("バックアップカメラも止めて", "Stop the backup camera too.", "備用攝影機也要停止錄影。"),
    ("隠しカメラがないか確認して", "Check that there are no hidden cameras.", "確認現場沒有隱藏攝影機。"),
    ("このカットは削除してください", "Please delete this take.", "請刪除這一段。"),
    ("この映像は公開しないで", "Do not publish this footage.", "不要公開這段影像。"),
    ("この映像は販売しないで", "Do not sell this footage.", "不要販售這段影像。"),
    ("SNSには載せないで", "Do not post it on social media.", "不要上傳到社群媒體。"),
    ("無断で転載しないで", "Do not repost it without permission.", "未經同意不要轉載。"),
    ("サムネイルに顔を使わないで", "Do not use the face in the thumbnail.", "縮圖不要使用臉部畫面。"),
    ("クレジットに本名を載せないで", "Do not put the legal name in the credits.", "片尾名單不要放本名。"),
    ("芸名だけを使って", "Use only the stage name.", "只使用藝名。"),
    ("同意書にない用途で使わないで", "Do not use it for purposes outside the consent form.", "不要用於同意書未列明的用途。"),
    ("公開前に映像を確認させて", "Let me review the footage before publication.", "公開前讓我確認影片。"),
    ("公開前に編集内容を確認させて", "Let me review the edit before publication.", "公開前讓我確認剪輯內容。"),
    ("誰が映像を見るのか教えてください", "Please tell me who will see the footage.", "請告訴我誰會看到影片。"),
    ("どこで公開するのか教えてください", "Please tell me where it will be published.", "請告訴我會在哪裡公開。"),
    ("保管期限を教えてください", "Please tell me the retention period.", "請告訴我資料保留期限。"),
    # Framing, continuity, and sound.
    ("カメラに向かって正面を向いて", "Face straight toward the camera.", "正面面向攝影機。"),
    ("カメラに背中を向けて", "Turn your back to the camera.", "背對攝影機。"),
    ("顔だけカメラに向けて", "Turn only your face toward the camera.", "只有臉轉向攝影機。"),
    ("ベッドの中央に移動して", "Move to the center of the bed.", "移到床鋪中央。"),
    ("フレームの中央に入って", "Move into the center of the frame.", "移到畫面中央。"),
    ("フレームから出ないで", "Stay inside the frame.", "不要離開畫面。"),
    ("顔がフレームから切れています", "The face is cut off in the frame.", "臉被畫面裁掉了。"),
    ("全身が入るようにして", "Make sure the full body is in the frame.", "讓全身都進入畫面。"),
    ("手元をアップで撮って", "Shoot a close-up of the hands.", "拍手部特寫。"),
    ("全身を引きで撮って", "Shoot a wide shot of the full body.", "用遠景拍攝全身。"),
    ("真上から撮って", "Shoot directly from above.", "從正上方拍攝。"),
    ("斜め前から撮って", "Shoot from a front oblique angle.", "從斜前方拍攝。"),
    ("マイクが服に擦れています", "The microphone is rubbing against the clothing.", "麥克風摩擦到衣服了。"),
    ("スタッフが映り込んでいます", "A staff member is visible in the shot.", "工作人員入鏡了。"),
    ("鏡にカメラが映っています", "The camera is visible in the mirror.", "鏡子裡拍到攝影機了。"),
    ("撮影を止めて音声を確認して", "Stop filming and check the audio.", "停止拍攝並確認音訊。"),
    ("今の台詞をもう一度お願いします", "Please repeat that line.", "剛才的台詞麻煩再說一次。"),
    ("今の台詞をゆっくりお願いします", "Please deliver that line more slowly.", "剛才的台詞麻煩說慢一點。"),
    ("台詞の最初からお願いします", "Please start again from the beginning of the line.", "麻煩從台詞開頭重新開始。"),
    ("同じ体位でもう一度お願いします", "Please do it once more in the same position.", "麻煩用同一個姿勢再來一次。"),
    ("体調を確認してから再開します", "We will resume after checking physical condition.", "確認身體狀況後再繼續。"),
    # Natural kana and particle-light forms commonly produced by ASR.
    ("もうやめてください", "Please stop now.", "請現在停下來。"),
    ("やめて下さい", "Please stop.", "請停下來。"),
    ("いきができない", "I cannot breathe.", "我無法呼吸。"),
    ("いきがくるしい", "I am having trouble breathing.", "我呼吸有困難。"),
    ("くるしかったらいって", "If you are in distress, say so.", "如果很難受就說出來。"),
    ("いたかったらいって", "If it hurts, say so.", "痛的話就說出來。"),
    ("くびをしめないで", "Do not choke.", "不要掐脖子。"),
    ("こんどーむをつけて", "Put on a condom.", "戴上保險套。"),
    ("こんどーむつけて", "Put on a condom.", "戴上保險套。"),
    ("こんどーむをはずさないで", "Do not remove the condom.", "不要拿掉保險套。"),
    ("まだいれないで", "Do not put it in yet.", "還不要放進去。"),
    ("ちつないにはださないで", "Do not ejaculate in the vagina.", "不要射在陰道內。"),
    ("かおはうつさないで", "Do not show the face.", "不要拍到臉。"),
    ("ほんみょうはいわないで", "Do not say the legal name.", "不要說出本名。"),
    ("さつえいをとめて", "Stop filming.", "停止拍攝。"),
    ("かめらをとめて", "Stop recording.", "停止錄影。"),
    ("ろくおんしないで", "Do not record audio.", "不要錄音。"),
    ("どういをてっかいします", "I withdraw my consent.", "我撤回同意。"),
)
_PHRASES += _SPECIALIZED_DOMAIN_EXPANSION

# Fixed, context-independent dialogue that compact MT models commonly
# mistranslate.  These groups stay separate so inventory growth is reviewable
# and tests can enforce that new rows are substantive rather than punctuation
# variants.
_COMMON_GREETINGS = (
    ("これはテストです", "This is a test.", "這是測試。"),
    ("テストを始めます", "The test will begin.", "現在開始測試。"),
    ("テストは終わりです", "The test is over.", "測試結束了。"),
    ("こんにちは", "Hello.", "你好。"),
    ("こんばんは", "Good evening.", "晚上好。"),
    ("おはようございます", "Good morning.", "早安。"),
    ("おやすみなさい", "Good night.", "晚安。"),
    ("はじめまして", "Nice to meet you.", "初次見面。"),
    ("お久しぶりです", "Long time no see.", "好久不見。"),
    ("さようなら", "Goodbye.", "再見。"),
    ("またね", "See you.", "再見。"),
    ("また明日", "See you tomorrow.", "明天見。"),
    ("また会いましょう", "Let's meet again.", "下次再見。"),
    ("行ってきます", "I'm heading out.", "我出門了。"),
    ("行ってらっしゃい", "Take care.", "路上小心。"),
    ("ただいま", "I'm home.", "我回來了。"),
    ("おかえりなさい", "Welcome home.", "歡迎回來。"),
    ("お元気ですか?", "How are you?", "你好嗎？"),
    ("元気です", "I'm well.", "我很好。"),
    ("来てくれてありがとう", "Thank you for coming.", "謝謝你來。"),
)

_COMMON_COURTESY = (
    ("ありがとう", "Thank you.", "謝謝。"),
    ("ありがとうございます", "Thank you very much.", "非常感謝。"),
    ("本当にありがとう", "Thank you so much.", "真的很謝謝你。"),
    ("どうもありがとう", "Thanks a lot.", "非常感謝。"),
    ("今日はありがとう", "Thank you for today.", "今天謝謝你。"),
    ("今日はありがとうございました", "Thank you for today.", "今天謝謝你。"),
    ("助かりました", "That was a big help.", "幫大忙了。"),
    ("どういたしまして", "You're welcome.", "不客氣。"),
    ("こちらこそありがとう", "Thank you too.", "我才要謝謝你。"),
    ("ごめんなさい", "I'm sorry.", "對不起。"),
    ("ごめんね", "Sorry.", "對不起。"),
    ("本当にごめんなさい", "I'm truly sorry.", "真的很對不起。"),
    ("申し訳ありません", "I sincerely apologize.", "非常抱歉。"),
    ("遅れてすみません", "Sorry I'm late.", "抱歉我遲到了。"),
    ("お待たせしました", "Thank you for waiting.", "讓你久等了。"),
    ("失礼しました", "I'm sorry about that.", "剛才失禮了。"),
    ("気にしないで", "Don't worry about it.", "別放在心上。"),
    ("お疲れさまです", "Thank you for your hard work.", "辛苦了。"),
    ("お疲れさまでした", "Thank you for your hard work.", "辛苦了。"),
    ("お願いいたします", "Please.", "麻煩您了。"),
    ("少々お待ちください", "Please wait a moment.", "請稍等。"),
    ("お待ちください", "Please wait.", "請稍候。"),
    ("もう一度お願いします", "One more time, please.", "麻煩再一次。"),
    ("確認をお願いします", "Please check it.", "麻煩確認一下。"),
)

_COMMON_UNDERSTANDING = (
    ("わかりました", "I understand.", "我明白了。"),
    ("分かりました", "I understand.", "我明白了。"),
    ("わかった", "Got it.", "我知道了。"),
    ("わかりません", "I don't understand.", "我不明白。"),
    ("分かりません", "I don't understand.", "我不明白。"),
    ("わからない", "I don't understand.", "我不懂。"),
    ("知らない", "I don't know.", "我不知道。"),
    ("知りません", "I don't know.", "我不知道。"),
    ("知っています", "I know.", "我知道。"),
    ("覚えています", "I remember.", "我記得。"),
    ("覚えていません", "I don't remember.", "我不記得。"),
    ("忘れました", "I forgot.", "我忘了。"),
    ("了解しました", "Understood.", "了解。"),
    ("承知しました", "Understood.", "明白了。"),
    ("聞こえました", "I heard it.", "我聽到了。"),
    ("聞こえません", "I can't hear it.", "我聽不到。"),
    ("よく聞こえません", "I can't hear it clearly.", "我聽不清楚。"),
    ("見えます", "I can see it.", "我看得到。"),
    ("見えません", "I can't see it.", "我看不到。"),
    ("よく見えません", "I can't see it clearly.", "我看不清楚。"),
    ("意味がわかりません", "I don't understand what it means.", "我不明白它的意思。"),
    ("もう一度言ってください", "Please say that again.", "請再說一次。"),
    ("もう一度説明してください", "Please explain that again.", "請再解釋一次。"),
    ("ゆっくり話してください", "Please speak slowly.", "請說慢一點。"),
    ("大きな声で話してください", "Please speak louder.", "請大聲一點。"),
    ("説明してください", "Please explain.", "請說明。"),
    ("確認してください", "Please check it.", "請確認。"),
    ("確認しました", "I've checked it.", "我確認過了。"),
    ("間違いありません", "That's correct.", "沒有錯。"),
)

_COMMON_DIRECTIONS = (
    ("ここに座ってください", "Please sit here.", "請坐在這裡。"),
    ("こちらに来てください", "Please come this way.", "請到這邊來。"),
    ("こちらを見てください", "Please look this way.", "請看這邊。"),
    ("少し待ってください", "Please wait a moment.", "請稍等一下。"),
    ("そのままお待ちください", "Please wait where you are.", "請在原地等候。"),
    ("ドアを開けてください", "Please open the door.", "請把門打開。"),
    ("ドアを閉めてください", "Please close the door.", "請把門關上。"),
    ("電気をつけてください", "Please turn on the lights.", "請把燈打開。"),
    ("電気を消してください", "Please turn off the lights.", "請把燈關掉。"),
    ("手を洗ってください", "Please wash your hands.", "請洗手。"),
    ("これを持ってください", "Please hold this.", "請拿著這個。"),
    ("ここに置いてください", "Please put it here.", "請放在這裡。"),
    ("そこに置いてください", "Please put it there.", "請放在那裡。"),
    ("中に入ってください", "Please come inside.", "請進來。"),
    ("外で待ってください", "Please wait outside.", "請在外面等。"),
    ("先に行ってください", "Please go ahead.", "請先走。"),
    ("一緒に来てください", "Please come with me.", "請跟我一起來。"),
    ("写真を見せてください", "Please show me the picture.", "請讓我看照片。"),
    ("もう一度見せてください", "Please show me again.", "請再讓我看一次。"),
    ("今何時ですか?", "What time is it?", "現在幾點？"),
    ("何時に始まりますか?", "What time does it start?", "幾點開始？"),
    ("何時に終わりますか?", "What time does it end?", "幾點結束？"),
)

_COMMON_DIALOGUE = (
    _COMMON_GREETINGS
    + _COMMON_COURTESY
    + _COMMON_UNDERSTANDING
    + _COMMON_DIRECTIONS
)
_PHRASES += _COMMON_DIALOGUE

# High-risk affirmative/negative minimal pairs retained for exhaustive tests.
# This is private metadata rather than matching logic: lookup remains an exact
# dictionary lookup and never searches for one member inside the other.
_NEGATION_SOURCE_PAIRS = (
    ("やめて", "やめないで"),
    ("止めて", "止めないで"),
    ("止まって", "止まらないで"),
    ("動いて", "動かないで"),
    ("手を離して", "手を離さないで"),
    ("急いで", "急がないで"),
    ("息を止めて", "息を止めないで"),
    ("痛い", "痛くない"),
    ("苦しい", "苦しくない"),
    ("気持ちいい", "気持ちよくない"),
    ("怖い", "怖くない"),
    ("リズムを変えて", "リズムを変えないで"),
    ("動きを止めて", "動きを止めないで"),
    ("角度を変えて", "角度を変えないで"),
    ("腰を動かして", "腰を動かさないで"),
    ("力を入れて", "力を入れないで"),
    ("力を抜いて", "力を抜かないで"),
    ("押して", "押さないで"),
    ("入れて", "入れないで"),
    ("挿れて", "挿れないで"),
    ("抜いて", "抜かないで"),
    ("中に出して", "中に出さないで"),
    ("触って", "触らないで"),
    ("さわって", "さわらないで"),
    ("見て", "見ないで"),
    ("こっち見て", "こっち見ないで"),
    ("キスして", "キスしないで"),
    ("脱いで", "脱がないで"),
    ("舐めて", "舐めないで"),
    ("なめて", "なめないで"),
    ("乳首を吸って", "乳首を吸わないで"),
    ("口を開けて", "口を開けないで"),
    ("舌を出して", "舌を出さないで"),
    ("飲み込んで", "飲み込まないで"),
    ("抱きしめて", "抱きしめないで"),
    ("名前を呼んで", "名前を呼ばないで"),
    ("目を閉じて", "目を閉じないで"),
    ("目を開けて", "目を開けないで"),
    ("カメラを見て", "カメラを見ないで"),
    ("レンズを見て", "レンズを見ないで"),
    ("動画を撮って", "動画を撮らないで"),
    ("写真を撮って", "写真を撮らないで"),
    ("カメラ回して", "カメラを回さないで"),
    ("服を脱いで", "服は脱がないで"),
    ("シャツを脱いで", "シャツは脱がないで"),
    ("ズボンを脱いで", "ズボンは脱がないで"),
    ("下着を脱いで", "下着は脱がないで"),
    ("ブラを外して", "ブラは外さないで"),
    ("ボタンを外して", "ボタンは外さないで"),
)

_QUESTION_SOURCE_PAIRS = (
    ("撮影を始めます", "撮影を始めてもいいですか?"),
    ("録音を始めます", "録音を始めてもいいですか?"),
    ("顔を撮ります", "顔を撮ってもいいですか?"),
    ("本名を出します", "本名を出してもいいですか?"),
    ("この映像を公開します", "この映像を公開してもいいですか?"),
    ("この部分を使います", "この部分を使ってもいいですか?"),
    ("録画を開始します", "録画を開始してもいいですか?"),
    ("音声を公開します", "音声を公開してもいいですか?"),
    ("撮影日を公開します", "撮影日を公開してもいいですか?"),
)


# Non-lexical cues are also exact-only.  In particular, this code does not try
# to infer arbitrary repeated kana as sexual content; unknown vocalizations go
# to the local model unchanged.
_NONLEXICAL = (
    ("あっ", "Ah.", "啊。"),
    ("あぁ", "Ah…", "啊……"),
    ("んっ", "Mm.", "嗯。"),
    ("んんっ", "Mmm.", "嗯……"),
    ("はぁ", "Hah…", "哈……"),
    ("はぁはぁ", "[panting]", "（喘氣聲）"),
    ("ふぅ", "Phew.", "呼……"),
    ("うっ", "Ugh.", "呃。"),
    ("きゃっ", "Ah!", "啊！"),
    ("[喘ぎ声]", "[moaning]", "（呻吟聲）"),
    ("(喘ぎ声)", "[moaning]", "（呻吟聲）"),
    ("[吐息]", "[breathing]", "（吐息聲）"),
    ("[息遣い]", "[heavy breathing]", "（急促呼吸聲）"),
    ("[笑い]", "[laughs]", "（笑聲）"),
    ("[キス音]", "[kissing sounds]", "（接吻聲）"),
    ("[ベッドのきしむ音]", "[bed creaking]", "（床鋪吱嘎聲）"),
    ("[喘ぎ]", "[moaning]", "（呻吟聲）"),
    ("[あえぎ声]", "[moaning]", "（呻吟聲）"),
    ("[うめき声]", "[groaning]", "（低吟聲）"),
    ("[呻吟]", "[moaning]", "（呻吟聲）"),
    ("[呼吸音]", "[breathing]", "（呼吸聲）"),
    ("[荒い息]", "[heavy breathing]", "（急促呼吸聲）"),
    ("[荒い息遣い]", "[heavy breathing]", "（急促呼吸聲）"),
    ("[深い呼吸]", "[deep breathing]", "（深呼吸聲）"),
    ("[息をのむ音]", "[gasps]", "（倒吸一口氣）"),
    ("[ため息]", "[sighs]", "（嘆氣聲）"),
    ("[長いため息]", "[long sigh]", "（長嘆聲）"),
    ("[笑い声]", "[laughs]", "（笑聲）"),
    ("[小さな笑い]", "[soft laughter]", "（輕笑聲）"),
    ("[含み笑い]", "[chuckles]", "（竊笑聲）"),
    ("[泣き声]", "[crying]", "（哭聲）"),
    ("[すすり泣き]", "[sobbing]", "（啜泣聲）"),
    ("[悲鳴]", "[scream]", "（尖叫聲）"),
    ("[小さな悲鳴]", "[soft scream]", "（輕微尖叫聲）"),
    ("[ささやき声]", "[whispering]", "（耳語聲）"),
    ("[囁き声]", "[whispering]", "（耳語聲）"),
    ("[小声]", "[speaking softly]", "（低聲說話）"),
    ("[衣擦れ]", "[clothes rustling]", "（衣物摩擦聲）"),
    ("[服の擦れる音]", "[clothes rustling]", "（衣物摩擦聲）"),
    ("[布の擦れる音]", "[fabric rustling]", "（布料摩擦聲）"),
    ("[水音]", "[water sounds]", "（水聲）"),
    ("[水の音]", "[water sounds]", "（水聲）"),
    ("[リップ音]", "[lip-smacking sounds]", "（嘴唇聲）"),
    ("[唇の音]", "[lip sounds]", "（嘴唇聲）"),
    ("[ベッドがきしむ音]", "[bed creaking]", "（床鋪吱嘎聲）"),
    ("[きしむ音]", "[creaking]", "（吱嘎聲）"),
    ("[床のきしむ音]", "[floor creaking]", "（地板吱嘎聲）"),
    ("[足音]", "[footsteps]", "（腳步聲）"),
    ("[近づく足音]", "[approaching footsteps]", "（接近的腳步聲）"),
    ("[ドアの音]", "[door sound]", "（門聲）"),
    ("[ドアが閉まる音]", "[door closes]", "（關門聲）"),
    ("[ドアが開く音]", "[door opens]", "（開門聲）"),
    ("[ノック]", "[knocking]", "（敲門聲）"),
    ("[ノック音]", "[knocking]", "（敲門聲）"),
    ("[拍手]", "[applause]", "（拍手聲）"),
    ("[カメラのシャッター音]", "[camera shutter]", "（相機快門聲）"),
    ("[シャッター音]", "[shutter sound]", "（快門聲）"),
    ("[録画開始音]", "[recording tone]", "（錄影提示音）"),
    ("[電子音]", "[electronic tone]", "（電子提示音）"),
    ("[着信音]", "[ringtone]", "（來電鈴聲）"),
    ("[通知音]", "[notification sound]", "（通知音）"),
    ("[物音]", "[noise]", "（聲響）"),
    ("[大きな物音]", "[loud noise]", "（巨大聲響）"),
    ("[沈黙]", "[silence]", "（沉默）"),
    ("[無言]", "[silence]", "（無言）"),
    ("[咳]", "[coughs]", "（咳嗽聲）"),
    ("[咳払い]", "[clears throat]", "（清喉嚨聲）"),
    ("[くしゃみ]", "[sneezes]", "（打噴嚏聲）"),
    ("[スタッフの声]", "[staff speaking]", "（工作人員說話聲）"),
    ("[遠くの声]", "[distant voices]", "（遠處人聲）"),
    ("[タイマー音]", "[timer beeps]", "（計時器聲）"),
    ("[アラーム音]", "[alarm]", "（警報聲）"),
    ("[拍子音]", "[rhythmic sound]", "（節拍聲）"),
)


def _build_memory(rows: tuple[tuple[str, str, str], ...]) -> dict[str, tuple[str, str]]:
    memory: dict[str, tuple[str, str]] = {}
    for source, english, taiwan in rows:
        key = normalize_cue(source)
        value = (english, taiwan)
        existing = memory.get(key)
        if existing is not None and existing != value:
            raise ValueError(f"Conflicting subtitle-domain phrase: {source!r}")
        memory[key] = value
    return memory


_PHRASE_MEMORY = _build_memory(_PHRASES)
_NONLEXICAL_MEMORY = _build_memory(_NONLEXICAL)
PHRASE_COUNT = len(_PHRASE_MEMORY)
NONLEXICAL_COUNT = len(_NONLEXICAL_MEMORY)


def _target_index(target_language: object) -> Optional[int]:
    key = _language_key(target_language)
    if key in _TARGET_ENGLISH:
        return 0
    if key in _TARGET_TAIWAN:
        return 1
    return None


def normalize_nonlexical(text: object, target_language: object) -> Optional[str]:
    """Translate a known non-lexical cue without guessing at unknown sounds."""

    target_index = _target_index(target_language)
    if target_index is None:
        return None
    translation = _NONLEXICAL_MEMORY.get(normalize_cue(text))
    return translation[target_index] if translation is not None else None


def exact_translation(
    text: object,
    source_language: object,
    target_language: object,
) -> Optional[str]:
    """Return a trusted whole-cue override, or ``None`` for the local model.

    No substring search, stemming, edit distance, or other fuzzy behavior is
    used.  This is particularly important for Japanese negation: a longer
    unknown cue containing ``やめて`` must not inherit the meaning "Stop."
    """

    if _language_key(source_language) not in _SOURCE_JAPANESE:
        return None
    target_index = _target_index(target_language)
    if target_index is None:
        return None

    nonlexical = _NONLEXICAL_MEMORY.get(normalize_cue(text))
    if nonlexical is not None:
        return nonlexical[target_index]
    translation = _PHRASE_MEMORY.get(normalize_cue(text))
    return translation[target_index] if translation is not None else None


# These replacements are intentionally small and unambiguous.  Full
# Simplified-to-Traditional conversion belongs to the model/OpenCC layer; this
# pass only aligns common output with Taiwan usage.
_TAIWAN_TERMS = (
    ("視頻", "影片"),
    ("軟件", "軟體"),
    ("硬件", "硬體"),
    ("網絡", "網路"),
    ("文件夾", "資料夾"),
    ("文件夹", "資料夾"),
    ("裏面", "裡面"),
    ("這裏", "這裡"),
    ("那裏", "那裡"),
    ("哪裏", "哪裡"),
    ("質量很好", "品質很好"),
    ("质量很好", "品質很好"),
    ("安全套", "保險套"),
    ("攝像機", "攝影機"),
    ("錄像", "錄影"),
    ("屏幕", "螢幕"),
    ("默認", "預設"),
    ("鼠標", "滑鼠"),
    ("鏈接", "連結"),
    ("快一點兒", "快一點"),
    ("慢一點兒", "慢一點"),
    ("輕一點兒", "輕一點"),
    ("舒服一點兒", "舒服一點"),
)


def postprocess_taiwan(text: object) -> str:
    """Apply conservative Taiwan terminology to model-produced cue text.

    The operation neither parses nor emits SRT metadata.  Line breaks are
    preserved so a caller can safely replace only an existing cue's text.
    """

    value = str(text or "")
    for source, replacement in _TAIWAN_TERMS:
        value = value.replace(source, replacement)
    value = re.sub(r"(?<=[\u3400-\u9fff])[ \t]+(?=[\u3400-\u9fff])", "", value)
    value = re.sub(r"(?<=[\u3400-\u9fff]),(?=[\u3400-\u9fff])", "，", value)
    value = re.sub(r"(?<=[\u3400-\u9fff]);(?=[\u3400-\u9fff])", "；", value)
    value = re.sub(r"(?<=[\u3400-\u9fff]):(?=[\u3400-\u9fff])", "：", value)
    value = re.sub(r"[ \t]+([，。！？；：,.!?;:])", r"\1", value)
    return value


_ENGLISH_SENTENCE_WORD_RE = re.compile(
    r"(^|(?<=[.!?])\s+)([\"'“‘(\[]*)([a-z][A-Za-z'’]*)",
    re.MULTILINE,
)
_ENGLISH_LOWERCASE_I_RE = re.compile(
    r"\bi(?=\b|['’](?:m|d|ll|ve|re)\b)"
)


def postprocess_english(text: object) -> str:
    """Conservatively polish casing from the compact local model.

    FuguMT's subtitle-style training data often emits an otherwise correct
    English sentence entirely in lowercase.  Only sentence-leading ASCII
    words and the standalone first-person pronoun are changed; spelling,
    wording, punctuation, and line breaks remain untouched.
    """

    value = _ENGLISH_LOWERCASE_I_RE.sub("I", str(text or ""))

    def capitalize_sentence_start(match: re.Match[str]) -> str:
        prefix, opening, word = match.groups()
        # Preserve intentionally styled names such as eBay and iPhone.
        if any(character.isupper() for character in word[1:]):
            return match.group(0)
        return prefix + opening + word[0].upper() + word[1:]

    return _ENGLISH_SENTENCE_WORD_RE.sub(capitalize_sentence_start, value)


__all__ = [
    "DOMAIN_VERSION",
    "DOMAIN_ENGINE_VERSION",
    "GLOSSARY_VERSION",
    "PHRASE_COUNT",
    "NONLEXICAL_COUNT",
    "normalize_cue",
    "exact_translation",
    "normalize_nonlexical",
    "postprocess_english",
    "postprocess_taiwan",
]
