#!/usr/bin/env python
# coding: utf-8
"""Discovers subtitles generated by FetchJAV's subtitle engine."""

from __future__ import annotations

import os
from typing import List, Optional

import config
from subtitle.models import SubtitleSourceType, SubtitleState, SubtitleTrack
from video_identity import video_code


LANG_LABELS = {
    'ja': 'Japanese (Generated)',
    'en': 'English (Generated)',
    'zh-TW': '繁體中文 (Generated)',
    'zh-CN': '簡體中文 (Generated)',
}


def find_generated_subtitles(video_info: dict, media_path: Optional[str] = None) -> List[SubtitleTrack]:
    """Find generated subtitle files (.ja.srt, .en.srt, .zh-TW.srt) for the given video."""
    tracks: List[SubtitleTrack] = []
    seen_paths = set()

    code = video_code(video_info)
    title = str((video_info or {}).get('title') or '')

    # Search candidates directories
    download_dir = os.path.abspath(getattr(config, 'savepath', 'download') or 'download')
    dirs_to_search = [download_dir]

    is_local_file = media_path and not str(media_path).lower().startswith(('http://', 'https://')) and os.path.isfile(media_path)
    if is_local_file:
        dirs_to_search.insert(0, os.path.dirname(os.path.abspath(media_path)))

    stems = []
    if is_local_file:
        stems.append(os.path.splitext(os.path.basename(media_path))[0])
    if code:
        stems.append(code)
    if title:
        stems.append(title)

    for search_dir in dirs_to_search:
        if not os.path.isdir(search_dir):
            continue

        for lang_code in ('ja', 'en', 'zh-TW', 'zh-CN'):
            for stem in stems:
                filename = f"{stem}.{lang_code}.srt"
                candidate_path = os.path.join(search_dir, filename)

                if os.path.isfile(candidate_path) and candidate_path not in seen_paths:
                    seen_paths.add(candidate_path)
                    label = LANG_LABELS.get(lang_code, f"{lang_code.upper()} (Generated)")
                    tracks.append(SubtitleTrack(
                        id=f"gen_{lang_code}_{len(tracks)}",
                        name=label,
                        language=lang_code,
                        language_code=lang_code,
                        source=SubtitleSourceType.GENERATED,
                        file_path=candidate_path,
                        format="srt",
                        state=SubtitleState.READY
                    ))

    return tracks
